/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as GcpRouteImport } from './routes/gcp'
import { Route as GwsRouteImport } from './routes/gws'
import { Route as OciRouteImport } from './routes/oci'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const GcpRoute = GcpRouteImport.update({
  id: '/gcp',
  path: '/gcp',
  getParentRoute: () => rootRouteImport,
} as any)
const GwsRoute = GwsRouteImport.update({
  id: '/gws',
  path: '/gws',
  getParentRoute: () => rootRouteImport,
} as any)
const OciRoute = OciRouteImport.update({
  id: '/oci',
  path: '/oci',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/gcp': typeof GcpRoute
  '/gws': typeof GwsRoute
  '/oci': typeof OciRoute
  '/processes': typeof ProcessesRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/gcp': typeof GcpRoute
  '/gws': typeof GwsRoute
  '/oci': typeof OciRoute
  '/processes': typeof ProcessesRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/gcp': typeof GcpRoute
  '/gws': typeof GwsRoute
  '/oci': typeof OciRoute
  '/processes': typeof ProcessesRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/academy' | '/gcp' | '/gws' | '/oci' | '/processes' | '/services'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/academy' | '/gcp' | '/gws' | '/oci' | '/processes' | '/services'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/gcp'
    | '/gws'
    | '/oci'
    | '/processes'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  GcpRoute: typeof GcpRoute
  GwsRoute: typeof GwsRoute
  OciRoute: typeof OciRoute
  ProcessesRoute: typeof ProcessesRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gcp': {
      id: '/gcp'
      path: '/gcp'
      fullPath: '/gcp'
      preLoaderRoute: typeof GcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gws': {
      id: '/gws'
      path: '/gws'
      fullPath: '/gws'
      preLoaderRoute: typeof GwsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oci': {
      id: '/oci'
      path: '/oci'
      fullPath: '/oci'
      preLoaderRoute: typeof OciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  GcpRoute: GcpRoute,
  GwsRoute: GwsRoute,
  OciRoute: OciRoute,
  ProcessesRoute: ProcessesRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
